apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-mri-app
  namespace: argocd   # Argo CD itself runs in this namespace
spec:
  project: default
  source:
    repoURL: 'https://github.com/akashjaiswal36/CI-Nodejs201225.git'
    targetRevision: main
    path: helm/devops-mri
    helm:
      releaseName: devops-mri
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default # where you want the app deployed
  syncPolicy:
    automated:
      prune: true      # remove resources not in Git
      selfHeal: true   # fix drift automatically