apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-mri-deploy
  labels:
    app: devops-mri
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-mri
  template:
    metadata:
      labels:
        app: devops-mri
    spec:
      containers:
      - name: devops-mri
        image: ajs3ra8/devops-mri:86477d5032d3b34cb220e6627973610fddf6b289
        ports:
        - containerPort: 3002
